export const grey = '#7a9e9f'
export const lightGrey = '#b8d8d8'
export const darkGrey = '#4f6367'
export const yellow = '#eef5db'
export const pink = '#fe5f55'
export const white = '#ffffff'
export const orange = '#ff6700'

// export const grey = '#c0c0c0'
// export const lighGrey = '#ebebeb'
// export const blue = '#3a6ea5'
// export const darkBlue = '#004E98'
// export const orange = '#ff6700'
