export const darkPrimary = '#1976D2'
export const lightPrimary = '#BBDEFB'
export const primary = '#2196F3'
export const textLight = '#FFFFFF'
export const accent = '#FF5722'
export const textPrimary = '#212121'
export const textSecondary = '#757575'
export const divider = '#BDBDBD'
